helmBs:
  - "/kafka/bschart"
  - "/couchbase/bschart"
  - "/kube-dashboard/bschart"
  - "/otel-collector/bschart"
  - "/jaeger/bschart"
  # - "/ollama/bschart"
  # - "/openweb/bschart"  

helmMs:
  - "/order-service/mschart"
  - "/product-service/mschart"
  - "/user-service/mschart"

helmTestBs:
  # - "/kube-dashboard/bschart"
  # - "/ollama/bschart"
  # - "/openweb/bschart"
  - "/kafka/bschart"

  
helmTestMs:
  - "/user-service/mschart"

valuesBs:
  - "/bs_global_values.yaml"

valuesMs:
  - "/ms_global_values.yaml"